Vagrant.configure("2") do |config|
  nodes = [
    { name: "cassandra01", hostname: "cassandra01", ip: "192.168.56.15" },
    { name: "cassandra02", hostname: "cassandra02", ip: "192.168.56.16" },
    { name: "cassandra03", hostname: "cassandra03", ip: "192.168.56.17" }
  ]

  box_name = "eurolinux-vagrant/rocky-9"
  memory = "4000"
  cpus = "2"
  provision_script = <<-SHELL
    # Update system to latest
    dnf update -y
    # Clear EuroLinux banner
    echo '' > /etc/motd
    # Reboot system
    reboot
  SHELL

  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.box = box_name
      vm.vm.hostname = node[:hostname]
      vm.vm.network "private_network", ip: node[:ip]
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = memory
        vb.cpus = cpus
      end
      vm.vm.provision "shell", inline: provision_script
    end
  end
end