---
- name: Enable and start Cassandra services
  hosts: all
  vars_files: "../definitions.yaml"
  become: true
  gather_facts: true
  tasks:
    - name: Install chkconfig
      ansible.builtin.package:
        name: chkconfig
        state: present

    - name: Enable Cassandra service
      ansible.builtin.service:
        name: cassandra
        enabled: true

    - name: Reboot Nodes
      ansible.builtin.reboot:
